### PR TITLE
feature: tags now are being parsed and represented visually based on …

### PR DESCRIPTION
**Pull request by adrianmg**
I've put together the first iteration of tags including in progress, new and shiny.

interaction

### CODE REVIEW

**Comment by mamuso** [comment]
A few questions,
- Are we crushing spaces here?
image
- Do we want to apply the same style to the Title tags?
image
- Do we want to do something with this case?
image

**Comment by adrianmg** [comment]
Do we want to support more than one tag? If so, why?

**Comment by adrianmg** [comment]
I didn't know we had tags in the title too… I'll work on that 👍

**Comment by adrianmg** [comment]
@mamuso take a look at this. I've simplified it so we no longer need pseudoelements and it's also scaling properly for different strings and cases (always starting from the right).

**Pull request merged**
